<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160719090439 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE langeland_zion_domain_model_devicecommand (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', timestamp DATETIME DEFAULT NULL, userid INT DEFAULT NULL, command VARCHAR(255) DEFAULT NULL, parameters LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', lifetime INT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, result LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_zion_domain_model_equipment (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', deviceclass CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_6B6807EE3957BCBE (deviceclass), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_zion_domain_model_network (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', `key` VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_zion_domain_model_devicenotification (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', device CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', timestamp DATETIME NOT NULL, notification VARCHAR(255) NOT NULL, parameters LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', indexed TINYINT(1) NOT NULL, INDEX IDX_AF31FFCF92FB68E (device), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_zion_domain_model_deviceclass (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) NOT NULL, version VARCHAR(255) DEFAULT NULL, ispermanent TINYINT(1) NOT NULL, offlinetimeout INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE langeland_zion_domain_model_device (identifier CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', network CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', deviceclass CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', `key` VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_52ADAFB8608487BC (network), INDEX IDX_52ADAFB83957BCBE (deviceclass), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_equipment ADD CONSTRAINT FK_6B6807EE3957BCBE FOREIGN KEY (deviceclass) REFERENCES langeland_zion_domain_model_deviceclass (identifier)');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_devicenotification ADD CONSTRAINT FK_AF31FFCF92FB68E FOREIGN KEY (device) REFERENCES langeland_zion_domain_model_device (identifier)');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_device ADD CONSTRAINT FK_52ADAFB8608487BC FOREIGN KEY (network) REFERENCES langeland_zion_domain_model_network (identifier)');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_device ADD CONSTRAINT FK_52ADAFB83957BCBE FOREIGN KEY (deviceclass) REFERENCES langeland_zion_domain_model_deviceclass (identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE langeland_zion_domain_model_device DROP FOREIGN KEY FK_52ADAFB8608487BC');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_equipment DROP FOREIGN KEY FK_6B6807EE3957BCBE');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_device DROP FOREIGN KEY FK_52ADAFB83957BCBE');
        $this->addSql('ALTER TABLE langeland_zion_domain_model_devicenotification DROP FOREIGN KEY FK_AF31FFCF92FB68E');
        $this->addSql('DROP TABLE langeland_zion_domain_model_devicecommand');
        $this->addSql('DROP TABLE langeland_zion_domain_model_equipment');
        $this->addSql('DROP TABLE langeland_zion_domain_model_network');
        $this->addSql('DROP TABLE langeland_zion_domain_model_devicenotification');
        $this->addSql('DROP TABLE langeland_zion_domain_model_deviceclass');
        $this->addSql('DROP TABLE langeland_zion_domain_model_device');
    }
}